- TagAndRelease.ps1
Update TagAndRelease.ps1 : add the LICENSE and NOTICES.md files to the binary release zip files.
> [BIA-446] Update release build process

- CONTRIBUTORS.md
This is an update of the contributors file for Analytics Middle Tier.  The contributors were pulled from the branch history on this repository and the predecessor repo found at https://github.com/Ed-Fi-Alliance.
> Updated contributors file

- NOTICES.md
- Update NOTICES.md
- List all third-party dependencies and their license terms.
> [BIA-461] Updated NOTICES.md

- src/EdFi.AnalyticsMiddleTier.DataStandard2/RLS/MSSQL/0010-View-rls_UserStudentDataAuthorization-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard31/RLS/MSSQL/0010-View-UserStudentDataAuthorization-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/RLS/MSSQL/0008-View-UserStudentDataAuthorization-Create.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/RLS/MSSQL/0010-View-UserStudentDataAuthorization-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/RLS/PostgreSQL/0008-View-rls_UserStudentDataAuthorization-Create.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/RLS/PostgreSQL/0010-View-rls_UserStudentDataAuthorization-Alter.sql
Added 0010-View-UserStudentDataAuthorization-Alter file to fix EF migrations order.
> [BI-667]  Fix migration file for UserStudentDataAuthorization.

- docs/installation.md
- src/EdFi.AnalyticsMiddleTier.Common/Component.cs
- src/EdFi.AnalyticsMiddleTier.Console/Program.cs
- src/EdFi.AnalyticsMiddleTier.DataStandard31/EdFi.AnalyticsMiddleTier.DataStandard31.csproj
- src/EdFi.AnalyticsMiddleTier.DataStandard32/EdFi.AnalyticsMiddleTier.DataStandard32.csproj
- Add a new option to install Equity Collection.
- Add Equity Collection Script folders.
- Update Installation doc file.
> [BIA-696] Create Equity Collection

- src/EdFi.AnalyticsMiddleTier.DataStandard2/Chrab/MSSQL/0004-View-ChronicAbsenteeismAttendanceFact-Update.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard31/Chrab/MSSQL/0004-View-ChronicAbsenteeismAttendanceFact-Update.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Chrab/MSSQL/0004-View-ChronicAbsenteeismAttendanceFact-Update.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Chrab/PostgreSQL/0004-View-ChronicAbsenteeismAttendanceFact-Update.sql
Updating chrab views to improve performance
> BIA-707 AMT - Attendance Calculation Performance Improvement

- src/EdFi.AnalyticsMiddleTier.DataStandard2/Base/MSSQL/0027-View-ContactPersonDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard31/Base/MSSQL/0025-View-ContactPersonDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Base/MSSQL/0025-View-ContactPersonDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Base/PostgreSQL/0026-View-ContactPersonDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.Tests/Classes/ContactPersonDim.cs
- src/EdFi.AnalyticsMiddleTier.Tests/Dimensions/When_querying_the_ContactPersonDim_view.cs
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/ContactPersonDim/132500_189856_should_have_PostalCode.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/ContactPersonDim/133012_190142_should_have_PostalCode.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/ContactPersonDim/154283_189864_should_not_have_PostalCode.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/ContactPersonDim/v_2/0001_ContactPersonDim_should_match_column_dictionary.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/ContactPersonDim/v_3_1/0001_ContactPersonDim_should_match_column_dictionary.xml
Adding PostalCode to ContactPersonDim view
> [BIA-726] Add zip code as an individual field on the ContactPersonDim view

- src/EdFi.AnalyticsMiddleTier.Common/DatabaseUninstallStrategyBase.cs
- src/EdFi.AnalyticsMiddleTier.Common/IUninstallStrategy.cs
- src/EdFi.AnalyticsMiddleTier.Common/PostgresUninstallStrategy.cs
- src/EdFi.AnalyticsMiddleTier.Tests/Common/IDataStandardTestFixtureBase.cs
- src/EdFi.AnalyticsMiddleTier.Tests/ITestHarnessBase.cs
- src/EdFi.AnalyticsMiddleTier.Tests/Operation/When_installing_base_views_fail.cs
- src/EdFi.AnalyticsMiddleTier.Tests/TestHarnessBase.cs
Add a new method to uninstall all the AMT objects (views, tables, functions, stored procedures and schemas).
> [BIA-791] Add a complete uninstall method (AMT)

- src/EdFi.AnalyticsMiddleTier.DataStandard31/Asmt/MSSQL/0020-View-AssessmentFact-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Asmt/MSSQL/0020-View-AssessmentFact-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Asmt/PostgreSQL/0020-View-AssessmentFact-Alter.sql
- src/EdFi.AnalyticsMiddleTier.Tests/Classes/AssessmentFact.cs
- src/EdFi.AnalyticsMiddleTier.Tests/Dimensions/When_querying_the_AssessmentFact_view.cs
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/AssessmentFact/0001_AssessmentFact_should_match_column_dictionary.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/AssessmentFact/2s3ch0knpb4val7uqve6mn269bavkdx2_should_have_AssessmentFactKey.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/AssessmentFact/3s4ch0knpb4va28uqve6mn269bavkdx2_should_have_AssessmentFactKey.xml
- Add an unique key (AssessmentFactKey) to AssessmentFact
- Update testcases to include the new column.
> [BIA-781] Add a unique identifier field to asmt_AssessmentFact

- src/EdFi.AnalyticsMiddleTier.DataStandard31/Equity/MSSQL/0009-View-StudentProgramCohortDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Equity/MSSQL/0004-View-StudentProgramCohortDim-Create.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Equity/MSSQL/0009-View-StudentProgramCohortDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Equity/PostgreSQL/0006-View-StudentProgramCohortDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.Tests/Classes/StudentProgramCohortDim.cs
- src/EdFi.AnalyticsMiddleTier.Tests/Dimensions/When_querying_the_StudentProgramCohortDim_view.cs
- src/EdFi.AnalyticsMiddleTier.Tests/EdFi.AnalyticsMiddleTier.Tests.csproj
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/StudentProgramCohortDim/0001_StudentProgramCohortDim_should_match_column_dictionary.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/StudentProgramCohortDim/189889_867530022_Cohort_Program_1_1666_867530_867530_20060814_CI_1000_should_have_CohortTypeDescriptor.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/StudentProgramCohortDim/189889_867530022_Cohort_Program_1_1666_867530_867530_20060814_CI_1000_should_have_EntryGradeLevelDescriptor.xml
Adding columns to view query from descriptor table
- EntryGradeDescriptor.Description AS EntryGradeLevelDescriptor
- CohortTypeDescriptor.Description AS CohortTypeDescriptor
Adding changes in both 3.1 and 3.2 version
Adding changes in both MSSQL and Postgress in version 3.2
Adding new columns to dictionary test for TeamCity testing routine
> BIA-777: changing StudentProgramCohortDim view to add entry level and cohort type descriptions

- src/EdFi.AnalyticsMiddleTier.DataStandard2/RLS/MSSQL/0011-View-rls_UserAuthorization-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard31/RLS/MSSQL/0011-View-UserAuthorization-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/RLS/MSSQL/0011-View-UserAuthorization-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/RLS/PostgreSQL/0011-View-rls_UserAuthorization-Alter.sql
- src/EdFi.AnalyticsMiddleTier.Tests/Classes/UserAuthorization.cs
- src/EdFi.AnalyticsMiddleTier.Tests/Dimensions/When_querying_the_UserAuthorization_view.cs
- src/EdFi.AnalyticsMiddleTier.Tests/EdFi.AnalyticsMiddleTier.Tests.csproj
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/UserAuthorization/0001_view_should_match_column_dictionary.json
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/UserAuthorization/MSSQL/v_2/querying_SectionPermission_should_have_SectionKeyPermission.json
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/UserAuthorization/MSSQL/v_3_1/querying_SectionPermission_should_have_SectionKeyPermission.json
Add SectionKeyPermission to UserAuthorization to return values related to SectionKey (SectionDim).
> [BIA-798] Update RLS_UserAuthorization to add a SectionPermission column by SectionKey (SectionDim)

- src/EdFi.AnalyticsMiddleTier.Tests/Dimensions/When_querying_the_UserDim_view.cs
- src/EdFi.AnalyticsMiddleTier.Tests/EdFi.AnalyticsMiddleTier.Tests.csproj
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/UserDim/PostgreSQL/v_3_2/0000_UserDim_Data_Load.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/UserDim/PostgreSQL/v_3_2/0001_UserDim_should_match_column_dictionary.xml
The tests coverage looks good.
> [BIA-654] - Adds Postgres tests: rls_UserDim View

- test/scripts/perf-testing-script.ps1
Replace Invoke-Sqlcmd by an ExecuteReader command to avoid load all rows in Memory. If a view returns a large list of rows the previous version failed with the error 'There is insufficient system memory in resource pool 'default' to run this query'
> [BIA-828] Update script to fix memory issue Student Engagement

- .github/workflows/build.yml
The only way I found to test this before merge, was to create a fork. 
On your fork, once this file is in main branch, it will start being executed when a push is done to main.  
And you can see it being executed if you go to the Actions page on Github.
> [BIA-475] - Creates a new workflow to build AMT.

- .github/workflows/build.yml
- eng/CreateTestDbAndSchema.ps1
- Update scripts to include docker support.
- Update workflow to add postgres.
- Update CreateScript
- Add parameter for database name.
> [BIA-895] Create a workflow on GitHub Actions that can get connected to the docker container and execute AMT tests

- .github/workflows/build.yml
- src/EdFi.AnalyticsMiddleTier.Tests/Common/ExceptionExtensionsTests.cs
Update message newline to use Environment.Newline.
Enable unit e integration tests.
> [BIA-477] GitHub Actions: Run Unit and Integration Tests

- src/EdFi.AnalyticsMiddleTier.Tests/PostgresConnectionString.cs
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/ChronicAbsenteeismAttendanceFact/MSSQL/v_3_3/0000_ChronicAbsenteeismAttendanceFact_Data_Load.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/ChronicAbsenteeismAttendanceFact/MSSQL/v_3_3/0001_ChronicAbsenteeismAttendanceFact_should_match_column_dictionary.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/ChronicAbsenteeismAttendanceFact/PostgreSQL/v_3_3/0000_ChronicAbsenteeismAttendanceFact_Data_Load.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/ChronicAbsenteeismAttendanceFact/PostgreSQL/v_3_3/0001_ChronicAbsenteeismAttendanceFact_should_match_column_dictionary.xml
Folders were created for SQL and PostgreSQL for DS3.3 Dataload. All 3.3 tests are working correctly.
> [BIA-900] - Implements tests for new ODS 5.3 - Chrab Collection

- .github/workflows/create-pre-release.yml
- build.ps1
Update Zip names to include the semantic version.
Update Zip structure to add all files to the root instead of add an extra folder.
> [BIA-917] Update release and build scripts to fix zip files

- src/EdFi.AnalyticsMiddleTier.DataStandard32/Engage/MSSQL/0010-Alter-View-AssignmentSubmissionFact.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard33/Engage/MSSQL/0006-Alter-View-AssignmentSubmissionFact.sql
Update the view engage_AssignmentSubmissionFact to include a column with bool value for upcoming assignments (DueDateTime > GETDATE()).
> [SESK-2] Add Upcoming Assignments to engage_AssignmentSubmissionFact

- src/EdFi.AnalyticsMiddleTier.DataStandard33/EPP/MSSQL/0001-View-CandidateSurveyDim-Create.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard33/EPP/MSSQL/0004-View-TermDescriptorDim-Create.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard33/EPP/PostgreSQL/0001-View-CandidateSurveyDim-Create.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard33/EPP/PostgreSQL/0004-View-TermDescriptorDim-Create.sql
- src/EdFi.AnalyticsMiddleTier.Tests/Classes/TermDescriptorDim.cs
- src/EdFi.AnalyticsMiddleTier.Tests/Dimensions/When_querying_the_TermDescriptorDim_view.cs
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/TermDescriptorDim/3570_should_have_CodeValue.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/TermDescriptorDim/3570_should_have_LastModifiedDate.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/TermDescriptorDim/3570_should_have_TermDescriptorKey.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/TermDescriptorDim/3570_should_return_one_record.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/TermDescriptorDim/MSSQL/v_3_3/0000_TermDescriptorDim_Data_Load.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/TermDescriptorDim/MSSQL/v_3_3/0001_view_should_match_column_dictionary.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/TermDescriptorDim/PostgreSQL/v_3_3/0000_TermDescriptorDim_Data_Load.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/TermDescriptorDim/PostgreSQL/v_3_3/0001_view_should_match_column_dictionary.xml
Add view script
Add test data.
Add TestCases
> [BIA-1020] Add TermDescriptorDim view

- build.ps1
- src/EdFi.AnalyticsMiddleTier.Console/EdFi.AnalyticsMiddleTier.Console.csproj
…efaultTargetOS to the same file.
> [BIA-1097] Removes RuntimeIdentifier from the console project file. Adds DockerDefaultTargetOS to the same file.

- Dockerfile
There are 2 changes on the dockerfile:
1. removes the release zip file after unzipping the content. 
2. Updated the AMT release version.
Build the image first, and then run the container.  If you need help to do that, use the documentation we added on [here](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-Analytics-Middle-Tier/blob/main/docs/docker.md) to know how to do it.
> [BIA-1098] - Makes the Dockerfile fully functional.

- .github/workflows/dependencies.yml
Script taken from [here](https://github.com/Ed-Fi-Exchange-OSS/Suite-3-Performance-Testing/blob/main/.github/workflows/dependencies.yml), based on [this documentation](https://techdocs.ed-fi.org/display/EDFIODS/Guidelines+for+Use+of+GitHub+Actions).
> [BIA-1102] Adds Dependency Review workflow.

- .github/workflows/build.yml
- docker/docker-compose.yml
- Update github actions with SQL Server 2019 and postgres 13
> BIA-1033: update github actions with SQL Server 2019 and postgres 13

- src/EdFi.AnalyticsMiddleTier.DataStandard31/Equity/MSSQL/0013-View-StudentProgramCohortDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Equity/MSSQL/0013-View-StudentProgramCohortDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Equity/PostgreSQL/0009-View-StudentProgramCohortDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard33/Equity/MSSQL/0007-View-StudentProgramCohortDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard33/Equity/PostgreSQL/0005-View-StudentProgramCohortDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.Tests/Dimensions/When_querying_the_StudentProgramCohortDim_view.cs
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/StudentProgramCohortDim/189890_867530023_Cohort_Program_2_1666_867531_867531_20060815_CI_1002_should_not_return_any_record.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/StudentProgramCohortDim/189890_867530023_Cohort_Program_2_1666_867532_867532_20060815_CI_1001_should_not_return_any_record.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/StudentProgramCohortDim/MSSQL/v_3_1/0000_StudentProgramCohortDim_Data_Load.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/StudentProgramCohortDim/MSSQL/v_3_2/0000_StudentProgramCohortDim_Data_Load.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/StudentProgramCohortDim/MSSQL/v_3_3/0000_StudentProgramCohortDim_Data_Load.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/StudentProgramCohortDim/PostgreSQL/v_3_2/0000_StudentProgramCohortDim_Data_Load.xml
- src/EdFi.AnalyticsMiddleTier.Tests/TestCases/StudentProgramCohortDim/PostgreSQL/v_3_3/0000_StudentProgramCohortDim_Data_Load.xml
- Add join to StudentCohortAssociation script.
- Update test data.
- Remove joins to Program and GeneralProgram.
- Add unit tests.
> [BIA-1219] Add StudentCohortAssociation to StudentProgramCohortDim

- src/EdFi.AnalyticsMiddleTier.DataStandard31/Base/MSSQL/0047-View-StudentSchoolDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Base/MSSQL/0047-View-StudentSchoolDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Base/PostgreSQL/0049-View-StudentSchoolDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard33/Base/MSSQL/0030-View-StudentSchoolDim-alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard33/Base/PostgreSQL/0031-View-StudentSchoolDim-alter.sql
Update AllStudentSchoolDim view (MSSQL and Postgres v 3.1, 3.2, 3.3)
> [BIA-1289] Update StudentSchoolDim LimitedEnglishProficiency, IsHispanic and Sex columns

- src/EdFi.AnalyticsMiddleTier.DataStandard31/Equity/MSSQL/0014-fn_GetStudentGradesSummary-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Equity/MSSQL/0014-fn_GetStudentGradesSummary-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard32/Equity/PostgreSQL/0010-View-StudentHistoryDim-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard33/Equity/MSSQL/0008-fn_GetStudentGradesSummary-Alter.sql
- src/EdFi.AnalyticsMiddleTier.DataStandard33/Equity/PostgreSQL/0006-View-StudentHistoryDim-Alter.sql
- Updated fn_GetStudentGradesSummary to use descriptor constant
> [BIA-1301]: Update fn_GetStudentGradesSummary to use descriptor constant

- README.md
> [BIA-1325] AMT readme updates

- build.ps1
Actual local output after this update.
```shell
PS Analytics-Middle-Tier> .\build.ps1 -Command publish
Building Version 4.0.0
Clean
AssemblyInfo
Generating .\src\Directory.Build.props
Compile
.NET SDK:
Version:           8.0.100
Commit:            57efcf1350
Workload version:  8.0.100-manifests.6a1e483a
Runtime Environment:
OS Name:     Windows
OS Version:  10.0.19045
OS Platform: Windows
RID:         win-x64
Base Path:   C:\Program Files\dotnet\sdk\8.0.100\
.NET workloads installed:
Workload version: 8.0.100-manifests.6a1e483a
There are no installed workloads to display.
Host:
Version:      8.0.0
Architecture: x64
Commit:       5535e31a71
.NET SDKs installed:
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.303 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
5.0.416 …
```
> [BIA-1351] Breaking change to publish command in .NET 8
